name: Automated health check

on:
  schedule:
    - cron: '0 0 6 * *'

jobs:
  health_check:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: jtalk/url-health-check-action@v3
        with:
          url: ${{secrets.PROD_URL}}
          max-attempts: 3
          retry-delay: 5s